apiVersion: v1
kind: Service
metadata:
    name: usamaspipelinesjavascriptdocker
    namespace: default
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: usamaspipelinesjavascriptdocker
